import "./globals.css";
import { VisualEditing } from "next-sanity";
import { draftMode } from "next/headers";
import { DisableDraftMode } from "@/components/DisableDraftMode";
import localFont from "next/font/local";
import LenisSmoothScroll from "@/components/LenisSmoothScroll";
import { SpeedInsights } from "@vercel/speed-insights/next";
import Layout from "@/components/Layout";

// Fonts
const standerd = localFont({
  src: [
    { path: "./fonts/Standerd-Regular.woff", weight: "400", style: "normal" },
    { path: "./fonts/Standerd-Medium.woff", weight: "500", style: "normal" },
    { path: "./fonts/Standerd-SemiBold.woff", weight: "600", style: "normal" },
    { path: "./fonts/Standerd-Bold.woff", weight: "700", style: "normal" },
  ],
  variable: "--font-body",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
});

const grotesk = localFont({
  src: [
    { path: "./fonts/TomatoGrotesk-Regular.woff", weight: "400", style: "normal" },
    { path: "./fonts/TomatoGrotesk-Medium.woff", weight: "500", style: "normal" },
    { path: "./fonts/TomatoGrotesk-Bold.woff", weight: "700", style: "normal" },
  ],
  variable: "--font-display",
  display: "swap",
  fallback: ["system-ui, sans-serif"],
}); 

export const metadata = {
  title: "Enigma",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <>
      <LenisSmoothScroll />
      <html lang="en">
        <body className={`${standerd.variable} ${grotesk.variable} bg-white text-black antialiased`}>
          <Layout children={children}/>
          {/* {children} */}
          {(await draftMode()).isEnabled && (
            <>
              <VisualEditing />
              <DisableDraftMode />
            </>
          )}
          <SpeedInsights />
        </body>
      </html>
    </>

  );
}